"""admin_centric_overhaul_sprint1

Revision ID: 8a7096d4afdc
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 16:40:57.757102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a7096d4afdc'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_slots',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'COMPLETED', 'CANCELLED', name='slot_status_enum', create_constraint=True), nullable=False),
    sa.Column('visit_result', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='visit_result_enum', create_constraint=True), nullable=False),
    sa.Column('visit_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.String(length=30), nullable=False),
    sa.Column('booked_by', sa.String(length=30), nullable=True),
    sa.Column('property_id', sa.String(length=30), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_slots_admin_id'), 'admin_slots', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_slots_booked_by'), 'admin_slots', ['booked_by'], unique=False)
    op.create_index(op.f('ix_admin_slots_property_id'), 'admin_slots', ['property_id'], unique=False)
    op.create_index(op.f('ix_admin_slots_slot_date'), 'admin_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_admin_slots_status'), 'admin_slots', ['status'], unique=False)
    op.add_column('payments', sa.Column('screenshot_url', sa.String(length=512), nullable=True))
    op.add_column('payments', sa.Column('verified_by', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['verified_by'], ['id'], ondelete='SET NULL')
    op.drop_column('payments', 'razorpay_order_id')
    op.drop_column('payments', 'method')
    op.drop_column('payments', 'reference_id')
    op.drop_column('payments', 'payout_processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payout_processed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('method', postgresql.ENUM('UPI', 'CARD', 'NETBANKING', 'WALLET', name='payment_method_enum'), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('razorpay_order_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'rejection_reason')
    op.drop_column('payments', 'admin_notes')
    op.drop_column('payments', 'verified_at')
    op.drop_column('payments', 'verified_by')
    op.drop_column('payments', 'screenshot_url')
    op.drop_index(op.f('ix_admin_slots_status'), table_name='admin_slots')
    op.drop_index(op.f('ix_admin_slots_slot_date'), table_name='admin_slots')
    op.drop_index(op.f('ix_admin_slots_property_id'), table_name='admin_slots')
    op.drop_index(op.f('ix_admin_slots_booked_by'), table_name='admin_slots')
    op.drop_index(op.f('ix_admin_slots_admin_id'), table_name='admin_slots')
    op.drop_table('admin_slots')
    # ### end Alembic commands ###
