"""agreement_admin_approval

Revision ID: c1fc379a59f4
Revises: 8a7096d4afdc
Create Date: 2026-03-14 16:51:56.538921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fc379a59f4'
down_revision: Union[str, None] = '8a7096d4afdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('approved_by', sa.String(length=30), nullable=True))
    op.add_column('agreements', sa.Column('advance_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'agreements', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.drop_column('agreements', 'advance_confirmed')
    op.drop_column('agreements', 'approved_by')
    # ### end Alembic commands ###
