"""add_properties_payments_jobs

Revision ID: e4bcef8135b8
Revises: c02aec16659d
Create Date: 2026-03-05 23:11:28.321759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4bcef8135b8'
down_revision: Union[str, None] = 'c02aec16659d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('APARTMENT', 'VILLA', 'INDEPENDENT_HOUSE', 'PENTHOUSE', name='property_type_enum', create_constraint=True), nullable=False),
    sa.Column('bhk', sa.String(length=20), nullable=False),
    sa.Column('sqft', sa.Integer(), nullable=False),
    sa.Column('furnishing', sa.Enum('FULLY_FURNISHED', 'SEMI_FURNISHED', 'UNFURNISHED', name='furnishing_enum', create_constraint=True), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('facing', sa.String(length=50), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=False),
    sa.Column('security_deposit', sa.Integer(), nullable=False),
    sa.Column('maintenance_charges', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('occupancy', sa.Enum('OCCUPIED', 'VACANT', name='occupancy_enum', create_constraint=True), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lease_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_occupancy'), 'properties', ['occupancy'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_rent'), 'properties', ['rent'], unique=False)
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'DISPUTED', 'CANCELLED', name='job_status_enum', create_constraint=True), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_time', sa.String(length=20), nullable=True),
    sa.Column('estimated_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_cost', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('property_id', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.String(length=30), nullable=True),
    sa.Column('provider_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_property_id'), 'jobs', ['property_id'], unique=False)
    op.create_index(op.f('ix_jobs_provider_id'), 'jobs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Enum('RENT', 'SERVICE', 'SECURITY_DEPOSIT', name='payment_type_enum', create_constraint=True), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OVERDUE', 'PAID', 'ESCROWED', 'REFUNDED', 'FAILED', name='payment_status_enum', create_constraint=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', name='payment_method_enum', create_constraint=True), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('payout_processed', sa.Boolean(), nullable=False),
    sa.Column('property_id', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_due_date'), 'payments', ['due_date'], unique=False)
    op.create_index(op.f('ix_payments_owner_id'), 'payments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payments_property_id'), 'payments', ['property_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_property_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_owner_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_provider_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_property_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_rent'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_occupancy'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
